---
name: Deploy Infrastructure
run-name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - '*.tf'
      - 'templates/*.*'
      - 'modules/*/*.tf'
      - '**.ini'
      - '**.xml'
      - '**.yml'
      - '**.yaml'
      - '**.toml'
      - '**.json'

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    uses: edelux/terraform/.github/workflows/oidc-deploy.yaml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}
...
